### ISSUE TITLE
Issue on page /Organizing_OS_Activities/presentation/readme.html

### ISSUE THREAD

**Issue by sophieclayton** [nasa/Transform-to-Open-Science-Book#6]
The link on this page that points to the folder with presentations is broken :(

this does not exist: https://github.com/nasa/Transform-to-Open-Science/blob/main/Organizing_OS_Activities/presentation

**Comment by bello-mart-isabella** [comment]
Thanks for catching! Here is where I was trying to point: https://github.com/nasa/Transform-to-Open-Science-Book/tree/main/Organizing_OS_Activities/presentation . I'll go through and fix all those links now.

**Comment by cgentemann** [comment]
Thank you!
https://github.com/nasa/Transform-to-Open-Science-Book/pull/10

**Comment by cgentemann** [comment]
@all-contributors add @sophieclayton for maintenance
