### ISSUE TITLE
Issue on page /Open_Science_Cookbook/Your_Organizations_Open_Science_Journey.html

### ISSUE THREAD

**Issue by andersoner** [nasa/Transform-to-Open-Science-Book#60]
Broken link here: NASA has some examples [here](https://science.nasa.gov/open-science/transform-to-open-science/stories).

**Comment by bressler95tops** [comment]
Thanks for bringing this to my attention @andersoner I will temporarily hide this link.  We were in the process of moving the articles at that link to our main blog website.

**Comment by bressler95tops** [comment]
Addressed this issue in PR #61.  @andersoner stay tuned since that link will come back once we have the content posted on our [blog website](https://blogs.nasa.gov/transformtoopenscience/).
